#
# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the eos_resilient_ecmp module
"""


class Resilient_ecmpArgs(object):  # pylint: disable=R0903
    """The arg spec for the eos_resilient_ecmp module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'elements': 'dict',
            'options': {'afi': {'choices': ['ipv4', 'ipv6'],
                                'required': True,
                                'type': 'str'},
                        'routes': {'elements': 'dict',
                                   'options': {'capacity': {'required': True,
                                                            'type': 'int'},
                                               'dest': {'required': True,
                                                        'type': 'str'},
                                               'redundancy': {'required': True,
                                                              'type': 'int'}},
                                   'required': True,
                                   'type': 'list'}},
            'type': 'list'},
 'running_config': {'type': 'str'},
 'state': {'choices': ['deleted',
                       'merged',
                       'overridden',
                       'replaced',
                       'gathered',
                       'rendered',
                       'parsed'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
